train: data/train.csv
test: data/test.csv
save: data/saved_model
batch_size: 8
gpu_capacity: 4
gpu_cooldown: 40
learning_rate: 0.8
epochs: 2
folds: 3

input:
  - qa_id
  - question_title
  - question_body
  - question_user_name
  - question_user_page
  - answer
  - answer_user_name
  - answer_user_page
  - url
  - category
  - host

id:
  - qa_id

target:
  - question_asker_intent_understanding
  - question_body_critical
  - question_conversational
  - question_expect_short_answer
  - question_fact_seeking
  - question_has_commonly_accepted_answer
  - question_interestingness_others
  - question_interestingness_self
  - question_multi_intent
  - question_not_really_a_question
  - question_opinion_seeking
  - question_type_choice
  - question_type_compare
  - question_type_consequence
  - question_type_definition
  - question_type_entity
  - question_type_instructions
  - question_type_procedure
  - question_type_reason_explanation
  - question_type_spelling
  - question_well_written
  - answer_helpful
  - answer_level_of_information
  - answer_plausible
  - answer_relevance
  - answer_satisfaction
  - answer_type_instructions
  - answer_type_procedure
  - answer_type_reason_explanation
  - answer_well_written

label:
  - target_vector

features:
  - text
  - mask
  - category